language: node_js
node_js: v6.11.1

# S: Build Lifecycle
install:
  - npm i

#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "tinymark"
  - git config user.email "crazybigmoon@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

cache:
  directories:
    - "node_modules"

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/tinymark/tinymark.github.io.git